### ISSUE TITLE
There appears to be no index.css files for the client to run successfully.

### ISSUE THREAD

**Issue by MikeGitIt** [psych0der/HourGlass#1]
Is this project just the scaffolding for an actual implementation? I was trying to run the project to see what the client frontend looks like and play around a bit. Thanks.

**Comment by psych0der** [comment]
This is a complete project. You can follow the instructions to build it yourself

**Comment by psych0der** [comment]
I'll deploy a working one soon

**Comment by psych0der** [comment]
Just committed the files. Accidently css files were ignored in .gitignore

**Comment by MikeGitIt** [comment]
Ok cool, thx!
